const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Employee = require('../src/models/employee.model');

dotenv.config();

const employees = [
  {
    employeeId: 'EMP-001',
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    phone: '555-0101',
    gender: 'Female',
    dateOfBirth: new Date('1990-05-15'),
    department: 'Engineering',
    designation: 'Senior Developer',
    joiningDate: new Date('2020-03-01'),
    salary: 120000,
    address: '123 Tech Lane, Silicon Valley, CA',
    status: 'Active',
  },
  {
    employeeId: 'EMP-002',
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.j@example.com',
    phone: '555-0102',
    gender: 'Male',
    dateOfBirth: new Date('1985-08-22'),
    department: 'Marketing',
    designation: 'Marketing Director',
    joiningDate: new Date('2018-07-15'),
    salary: 95000,
    address: '456 Market St, New York, NY',
    status: 'Active',
  },
  {
    employeeId: 'EMP-003',
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.b@example.com',
    phone: '555-0103',
    gender: 'Male',
    dateOfBirth: new Date('1992-11-30'),
    department: 'Sales',
    designation: 'Sales Representative',
    joiningDate: new Date('2021-01-10'),
    salary: 60000,
    address: '789 Commerce Ave, Chicago, IL',
    status: 'Active',
  },
  {
    employeeId: 'EMP-004',
    firstName: 'Diana',
    lastName: 'Prince',
    email: 'diana.p@example.com',
    phone: '555-0104',
    gender: 'Female',
    dateOfBirth: new Date('1988-03-14'),
    department: 'Human Resources',
    designation: 'HR Manager',
    joiningDate: new Date('2019-05-20'),
    salary: 85000,
    address: '101 HR Blvd, Austin, TX',
    status: 'Active',
  },
  {
    employeeId: 'EMP-005',
    firstName: 'Evan',
    lastName: 'Wright',
    email: 'evan.w@example.com',
    phone: '555-0105',
    gender: 'Male',
    dateOfBirth: new Date('1995-07-07'),
    department: 'Engineering',
    designation: 'Junior Developer',
    joiningDate: new Date('2022-09-01'),
    salary: 70000,
    address: '202 Code St, Seattle, WA',
    status: 'Active',
  },
  {
    employeeId: 'EMP-006',
    firstName: 'Fiona',
    lastName: 'Gallagher',
    email: 'fiona.g@example.com',
    phone: '555-0106',
    gender: 'Female',
    dateOfBirth: new Date('1991-09-25'),
    department: 'Finance',
    designation: 'Financial Analyst',
    joiningDate: new Date('2020-11-15'),
    salary: 80000,
    address: '303 Wealth Way, Boston, MA',
    status: 'Active',
  },
  {
    employeeId: 'EMP-007',
    firstName: 'George',
    lastName: 'Miller',
    email: 'george.m@example.com',
    phone: '555-0107',
    gender: 'Male',
    dateOfBirth: new Date('1980-12-12'),
    department: 'Operations',
    designation: 'Operations Manager',
    joiningDate: new Date('2015-04-10'),
    salary: 110000,
    address: '404 Ops Road, Denver, CO',
    status: 'On Leave',
  },
  {
    employeeId: 'EMP-008',
    firstName: 'Hannah',
    lastName: 'Abbott',
    email: 'hannah.a@example.com',
    phone: '555-0108',
    gender: 'Female',
    dateOfBirth: new Date('1994-02-28'),
    department: 'Marketing',
    designation: 'Content Creator',
    joiningDate: new Date('2021-08-01'),
    salary: 65000,
    address: '505 Creative Lane, Portland, OR',
    status: 'Active',
  },
  {
    employeeId: 'EMP-009',
    firstName: 'Ian',
    lastName: 'Malcolm',
    email: 'ian.m@example.com',
    phone: '555-0109',
    gender: 'Male',
    dateOfBirth: new Date('1987-10-10'),
    department: 'Engineering',
    designation: 'DevOps Engineer',
    joiningDate: new Date('2019-12-01'),
    salary: 115000,
    address: '606 Cloud St, San Francisco, CA',
    status: 'Active',
  },
  {
    employeeId: 'EMP-010',
    firstName: 'Julia',
    lastName: 'Roberts',
    email: 'julia.r@example.com',
    phone: '555-0110',
    gender: 'Female',
    dateOfBirth: new Date('1993-06-18'),
    department: 'Sales',
    designation: 'Sales Manager',
    joiningDate: new Date('2020-02-15'),
    salary: 90000,
    address: '707 Deal Ave, Atlanta, GA',
    status: 'Active',
  },
  {
    employeeId: 'EMP-011',
    firstName: 'Kevin',
    lastName: 'Hart',
    email: 'kevin.h@example.com',
    phone: '555-0111',
    gender: 'Male',
    dateOfBirth: new Date('1989-04-05'),
    department: 'Human Resources',
    designation: 'Recruiter',
    joiningDate: new Date('2021-05-10'),
    salary: 75000,
    address: '808 Talent Blvd, Miami, FL',
    status: 'Inactive',
  },
  {
    employeeId: 'EMP-012',
    firstName: 'Laura',
    lastName: 'Palmer',
    email: 'laura.p@example.com',
    phone: '555-0112',
    gender: 'Female',
    dateOfBirth: new Date('1996-01-20'),
    department: 'Engineering',
    designation: 'QA Engineer',
    joiningDate: new Date('2022-03-01'),
    salary: 80000,
    address: '909 Bug Lane, Seattle, WA',
    status: 'Active',
  },
  {
    employeeId: 'EMP-013',
    firstName: 'Michael',
    lastName: 'Scott',
    email: 'michael.s@example.com',
    phone: '555-0113',
    gender: 'Male',
    dateOfBirth: new Date('1975-08-16'),
    department: 'Management',
    designation: 'Regional Manager',
    joiningDate: new Date('2010-01-05'),
    salary: 150000,
    address: '1010 Paper St, Scranton, PA',
    status: 'Active',
  },
  {
    employeeId: 'EMP-014',
    firstName: 'Nina',
    lastName: 'Dobrev',
    email: 'nina.d@example.com',
    phone: '555-0114',
    gender: 'Female',
    dateOfBirth: new Date('1992-05-09'),
    department: 'Marketing',
    designation: 'SEO Specialist',
    joiningDate: new Date('2020-09-15'),
    salary: 70000,
    address: '1111 Search Ave, Las Vegas, NV',
    status: 'Terminated',
  },
  {
    employeeId: 'EMP-015',
    firstName: 'Oscar',
    lastName: 'Isaac',
    email: 'oscar.i@example.com',
    phone: '555-0115',
    gender: 'Male',
    dateOfBirth: new Date('1986-11-21'),
    department: 'Engineering',
    designation: 'Frontend Developer',
    joiningDate: new Date('2018-06-10'),
    salary: 105000,
    address: '1212 UI Blvd, Austin, TX',
    status: 'Active',
  }
];

const seedDB = async () => {
  try {
    const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/employee-management';
    await mongoose.connect(uri);
    console.log('MongoDB Connected for Seeding');

    // Clear existing
    await Employee.deleteMany();
    console.log('Existing employees deleted');

    // Insert new
    await Employee.insertMany(employees);
    console.log('15 realistic employees inserted successfully!');

    process.exit(0);
  } catch (error) {
    console.error('Error with Seeder:', error);
    process.exit(1);
  }
};

seedDB();
